- name: For the default IPv4 adpater, show IP separate from MAC, then IPv4 and MAC on the same line.
  hosts: aur
  gather_facts: True
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_default_ipv4.macaddress
    - debug: msg=" ip:mac {{ ansible_default_ipv4.address }} ':' {{ ansible_default_ipv4.macaddress }}"
